In [31]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from seaborn import set_style

set_style('whitegrid')

In [32]:
select_measure_data = pd.read_excel('../data/2024_county_health_release_data_-_v1.xlsx', sheet_name=1, header=1) 
#sheet 1 contains the select measure data; header=1 removes the hierarchical column name structure.
#You will may need to update the file path to your data

In [33]:
select_measure_data.head()

,FIPS,State,County,Unreliable,Deaths,Years of Potential Life Lost Rate,95% CI - Low,95% CI - High,National Z-Score,YPLL Rate (Hispanic (all races)),...,% Drive Alone (Hispanic) 95% CI - Low,% Drive Alone (Hispanic) 95% CI - High,% Drive Alone (White),% Drive Alone (White) 95% CI - Low,% Drive Alone (White) 95% CI - High,# Workers who Drive Alone,% Long Commute - Drives Alone,95% CI - Low.19,95% CI - High.19,National Z-Score.33
0,1000,Alabama,NaN,NaN,98140.0,11415.734833,11307.652847,11523.816818,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2183677.0,35.2,34.770402,35.629598,NaN
1,1001,Alabama,Autauga,NaN,942.0,9407.948438,8508.880150,10307.016727,-0.158592,NaN,...,NaN,NaN,80.846691,75.707887,85.985495,27031.0,42.9,37.580831,48.219169,0.770216
2,1003,Alabama,Baldwin,NaN,3789.0,8981.575353,8514.700923,9448.449784,-0.282176,4784.741236,...,52.360312,72.248027,80.137935,78.359852,81.916017,105865.0,37.9,35.383728,40.416272,0.375235
3,1005,Alabama,Barbour,NaN,579.0,13138.848362,11474.734018,14802.962705,0.922816,NaN,...,NaN,NaN,84.432651,80.693766,88.171536,8341.0,36.7,30.463148,42.936852,0.280439
4,1007,Alabama,Bibb,NaN,501.0,12675.434581,10964.290135,14386.579028,0.788495,NaN,...,NaN,NaN,NaN,NaN,NaN,8064.0,53.8,45.204744,62.395256,1.631275

In [34]:
additional_measure_data = pd.read_excel('../data/2024_county_health_release_data_-_v1.xlsx', sheet_name=3, header=1)

In [35]:
additional_measure_data.FIPS.all() == select_measure_data.FIPS.all()
#just checking that the county labels are identical and all properly accounted for in both sheets

np.True_

In [36]:
select_measure_data.set_index(['FIPS','State','County'], inplace=True)
additional_measure_data.set_index(['FIPS','State','County'], inplace=True)
#set to a multiindex to make sure these columns are kept in each dataframe without needing to worry about duplication.
#There may be a better way of doing this, especially given that I want to undo the multi-index later

Below, we import the feature lists we need:

In [1]:
%run features.ipynb

In [38]:
full_feature_list = select_measure_data_features + additional_measure_data_features #both are from the features file
len(full_feature_list)

85

In [40]:
additional_measure_data_features[2]

'Child Mortality Rate'

In [41]:
select_measure_data = select_measure_data[select_measure_data_features]

In [42]:
select_measure_data.head()

,,,Deaths,Years of Potential Life Lost Rate,% Fair or Poor Health,Average Number of Physically Unhealthy Days,Average Number of Mentally Unhealthy Days,% Low Birthweight,% Adults Reporting Currently Smoking,% Adults with Obesity,Food Environment Index,% Physically Inactive,...,% Children in Poverty,Income Ratio,% Children in Single-Parent Households,Social Association Rate,Injury Death Rate,Average Daily PM2.5,Presence of Water Violation,% Severe Housing Problems,% Drive Alone to Work,% Long Commute - Drives Alone
FIPS,State,County,,,,,,,,,,,,,,,,,,,,,
1000,Alabama,NaN,98140.0,11415.734833,17.8,3.934735,5.869320,10.480008,17.9,40.6,5.4,29.9,...,21.8,5.212688,30.587530,11.694730,90.379699,9.3,NaN,13.081247,82.825024,35.2
1001,Alabama,Autauga,942.0,9407.948438,17.3,3.910265,5.703204,9.871335,16.9,38.9,6.7,29.1,...,15.7,4.637675,22.702506,12.691429,68.033478,10.0,No,15.375696,85.427842,42.9
1003,Alabama,Baldwin,3789.0,8981.575353,15.2,3.730943,5.373666,8.124318,15.0,37.2,7.5,27.6,...,16.1,4.482449,19.051287,9.653397,77.507985,7.6,Yes,12.427866,81.346999,37.9
1005,Alabama,Barbour,579.0,13138.848362,27.3,5.023488,6.014294,12.272491,25.0,43.4,6.0,40.2,...,37.7,5.576797,50.660451,8.412113,85.215853,9.4,No,15.075107,82.052512,36.7
1007,Alabama,Bibb,501.0,12675.434581,22.0,4.552795,5.824583,9.828571,22.0,39.6,7.6,36.0,...,25.5,5.669237,30.713370,8.897985,99.933081,9.8,No,12.258953,87.983631,53.8

In [43]:
len(select_measure_data.columns)

35

In [44]:
additional_measure_data = additional_measure_data[additional_measure_data_features]

In [45]:
len(additional_measure_data.columns)

50

In [46]:
national_data = select_measure_data.join(additional_measure_data, lsuffix='_s', rsuffix='_a')

In [47]:
len(national_data.columns)

85

At this point, we have one data frame for the national data on 35 calculated features from the Select Measure Data (```select_measure_data```), one data frame for 51 calculated features from the Additional Measure Data (```additional_measure_data```), and one data frame for the combined list of features (```national_data```). Currently the data are multi-indexed on FIPS, State, and County, for readability. Let's change that to FIPS on all three frames.

In [65]:
select_measure_data.reset_index(inplace=True)
additional_measure_data.reset_index(inplace=True)
national_data.reset_index(inplace=True)

In [66]:
select_measure_data.set_index(['FIPS'], inplace=True)
additional_measure_data.set_index(['FIPS'], inplace=True)
national_data.set_index(['FIPS'], inplace=True)

In [64]:
select_measure_data.describe()

,Deaths,Years of Potential Life Lost Rate,% Fair or Poor Health,Average Number of Physically Unhealthy Days,Average Number of Mentally Unhealthy Days,% Low Birthweight,% Adults Reporting Currently Smoking,% Adults with Obesity,Food Environment Index,% Physically Inactive,...,% Unemployed,% Children in Poverty,Income Ratio,% Children in Single-Parent Households,Social Association Rate,Injury Death Rate,Average Daily PM2.5,% Severe Housing Problems,# Workers who Drive Alone,% Long Commute - Drives Alone
count,2937.000000,2937.000000,3194.000000,3194.000000,3194.000000,3096.000000,3194.000000,3194.000000,3159.000000,3194.000000,...,3193.000000,3193.000000,3179.000000,3193.000000,3194.000000,3088.000000,3166.000000,3194.000000,3.194000e+03,3194.000000
mean,3084.906367,9927.126729,17.680964,3.887762,5.212354,8.363311,18.979869,37.292642,7.542703,26.603726,...,3.591533,19.367303,4.552661,23.905170,11.283639,96.069451,7.526737,12.851362,9.811973e+04,32.986819
std,16883.777093,3434.598181,4.536947,0.648025,0.613844,2.081590,4.110126,4.576466,1.199885,5.229915,...,1.224768,8.360806,0.803403,10.202613,5.828974,28.495495,1.712560,4.401615,5.971768e+05,12.658577
min,48.000000,2771.454704,8.400000,2.261790,3.185544,3.053435,7.000000,17.400000,0.000000,12.000000,...,0.572082,2.400000,1.651643,0.000000,0.000000,26.625917,0.900000,0.000000,3.600000e+01,0.000000
25%,263.000000,7566.637341,14.200000,3.385923,4.814033,6.949073,16.400000,35.000000,6.900000,23.000000,...,2.729868,13.400000,4.019159,17.177027,7.889021,76.820195,6.500000,10.208985,4.429000e+03,23.600000
50%,560.000000,9429.474414,16.800000,3.866092,5.229221,8.073939,18.700000,37.600000,7.700000,26.200000,...,3.414634,18.000000,4.435789,22.244489,10.767694,93.517419,7.700000,12.250041,1.117000e+04,32.400000
75%,1382.000000,11735.843802,20.700000,4.332715,5.626761,9.296569,21.500000,40.200000,8.400000,30.000000,...,4.200831,24.000000,4.945139,28.662047,14.073401,110.955984,8.800000,14.776089,3.299775e+04,41.675000
max,420722.000000,41152.261127,38.000000,6.836834,7.388805,19.178082,43.000000,52.500000,10.000000,47.000000,...,14.667733,88.700000,10.532338,78.519291,59.435364,315.568022,15.600000,61.142857,1.835347e+07,73.300000

In [76]:
select_measure_data.isna().sum()

State                                            0
County                                          51
Deaths                                         264
Years of Potential Life Lost Rate              264
% Fair or Poor Health                            7
Average Number of Physically Unhealthy Days      7
Average Number of Mentally Unhealthy Days        7
% Low Birthweight                              105
% Adults Reporting Currently Smoking             7
% Adults with Obesity                            7
Food Environment Index                          42
% Physically Inactive                            7
% With Access to Exercise Opportunities         52
% Excessive Drinking                             7
% Driving Deaths with Alcohol Involvement       34
Chlamydia Rate                                 153
Teen Birth Rate                                223
% Uninsured                                      8
Primary Care Physicians Rate                   164
Dentist Rate                                    94
Mental Health Provider Rate                    192
Preventable Hospitalization Rate                77
% with Annual Mammogram                         29
% Vaccinated                                    27
% Completed High School                          7
% Some College                                   7
% Unemployed                                     8
% Children in Poverty                            8
Income Ratio                                    22
% Children in Single-Parent Households           8
Social Association Rate                          7
Injury Death Rate                              113
Average Daily PM2.5                             35
Presence of Water Violation                    110
% Severe Housing Problems                        7
# Workers who Drive Alone                        7
% Long Commute - Drives Alone                    7
dtype: int64

In [77]:
select_measure_data.dtypes

State                                           object
County                                          object
Deaths                                         float64
Years of Potential Life Lost Rate              float64
% Fair or Poor Health                          float64
Average Number of Physically Unhealthy Days    float64
Average Number of Mentally Unhealthy Days      float64
% Low Birthweight                              float64
% Adults Reporting Currently Smoking           float64
% Adults with Obesity                          float64
Food Environment Index                         float64
% Physically Inactive                          float64
% With Access to Exercise Opportunities        float64
% Excessive Drinking                           float64
% Driving Deaths with Alcohol Involvement      float64
Chlamydia Rate                                 float64
Teen Birth Rate                                float64
% Uninsured                                    float64
Primary Care Physicians Rate                   float64
Dentist Rate                                   float64
Mental Health Provider Rate                    float64
Preventable Hospitalization Rate               float64
% with Annual Mammogram                        float64
% Vaccinated                                   float64
% Completed High School                        float64
% Some College                                 float64
% Unemployed                                   float64
% Children in Poverty                          float64
Income Ratio                                   float64
% Children in Single-Parent Households         float64
Social Association Rate                        float64
Injury Death Rate                              float64
Average Daily PM2.5                            float64
Presence of Water Violation                     object
% Severe Housing Problems                      float64
# Workers who Drive Alone                      float64
% Long Commute - Drives Alone                  float64
dtype: object

In [78]:
additional_measure_data.isna().sum()

State                                                     0
County                                                   51
Life Expectancy                                          80
# Deaths                                                 62
Child Mortality Rate                                   1112
Infant Mortality Rate                                  1944
% Frequent Physical Distress                              7
% Frequent Mental Distress                                7
% Adults with Diabetes                                    7
HIV Prevalence Rate                                     462
% Food Insecure                                           7
% Limited Access to Healthy Foods                        42
Drug Overdose Mortality Rate                           1251
% Insufficient Sleep                                     10
% Uninsured Adults                                        8
% Uninsured Children                                      8
Cohort Size                                             685
High School Graduation Rate                             685
% Disconnected Youth                                   1977
Average Grade Performance                               376
Average Grade Performance.1                             463
School Funding Adequacy                                  93
Women's Median Earnings                                  13
Men's Median Earnings                                    13
Median Household Income                                   8
% Enrolled in Free or Reduced Lunch                     559
% Household Income Required for Child Care Expenses       8
Child Care Centers per 1,000 Children                   159
Homicide Rate                                          1774
# Deaths.3                                              723
Suicide Rate (Age-Adjusted)                             723
Crude Rate                                              723
Firearm Fatalities Rate                                 871
Motor Vehicle Mortality Rate                            462
Juvenile Arrest Rate                                   1255
% Voter Turnout                                          38
% Census Participation                                   60
Traffic Volume                                           38
% Homeowners                                              7
# Households with Severe Cost Burden                     12
% Households with Severe Cost Burden                     12
% Households with Broadband Access                        7
% Less than 18 Years of Age                               7
% 65 and Over                                             7
% Black                                                   7
% American Indian or Alaska Native                        7
% Asian                                                   7
% Native Hawaiian or Other Pacific Islander               7
% Hispanic                                                7
% Non-Hispanic White                                      7
% Not Proficient in English                               7
% Female                                                  7
% Rural                                                   7
dtype: int64

In [79]:
additional_measure_data.dtypes

State                                                   object
County                                                  object
Life Expectancy                                        float64
# Deaths                                               float64
Child Mortality Rate                                   float64
Infant Mortality Rate                                  float64
% Frequent Physical Distress                           float64
% Frequent Mental Distress                             float64
% Adults with Diabetes                                 float64
HIV Prevalence Rate                                    float64
% Food Insecure                                        float64
% Limited Access to Healthy Foods                      float64
Drug Overdose Mortality Rate                           float64
% Insufficient Sleep                                   float64
% Uninsured Adults                                     float64
% Uninsured Children                                   float64
Cohort Size                                            float64
High School Graduation Rate                            float64
% Disconnected Youth                                   float64
Average Grade Performance                              float64
Average Grade Performance.1                            float64
School Funding Adequacy                                float64
Women's Median Earnings                                float64
Men's Median Earnings                                  float64
Median Household Income                                float64
% Enrolled in Free or Reduced Lunch                    float64
% Household Income Required for Child Care Expenses    float64
Child Care Centers per 1,000 Children                  float64
Homicide Rate                                          float64
# Deaths.3                                             float64
Suicide Rate (Age-Adjusted)                            float64
Crude Rate                                             float64
Firearm Fatalities Rate                                float64
Motor Vehicle Mortality Rate                           float64
Juvenile Arrest Rate                                   float64
% Voter Turnout                                        float64
% Census Participation                                 float64
Traffic Volume                                         float64
% Homeowners                                           float64
# Households with Severe Cost Burden                   float64
% Households with Severe Cost Burden                   float64
% Households with Broadband Access                     float64
% Less than 18 Years of Age                            float64
% 65 and Over                                          float64
% Black                                                float64
% American Indian or Alaska Native                     float64
% Asian                                                float64
% Native Hawaiian or Other Pacific Islander            float64
% Hispanic                                             float64
% Non-Hispanic White                                   float64
% Not Proficient in English                            float64
% Female                                               float64
% Rural                                                float64
dtype: object

In select_measure_data and additional_measure_data, there are many null values, but nearly every column is numeric, as expected. Only "Presence of Water Violation" in select_measure_data has an 'object' datatype. This indicates that, apart from dealing with null values, minimal cleaning should be needed. We may need to watch for wildly out-of-range values, but we can do this in our outlier analysis.