In [1]:
import numpy as np
import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
file_path = '../data/national_data_master.csv'
data = pd.read_csv(file_path)

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3201 entries, 0 to 3200
Data columns (total 88 columns):
 #   Column                                               Non-Null Count  Dtype
---  ------                                               --------------  -----
 0   FIPS                                                 3201 non-null   int64
 1   State                                                3201 non-null   object
 2   County                                               3150 non-null   object
 3   Deaths                                               2937 non-null   float64
 4   Years of Potential Life Lost Rate                    2937 non-null   float64
 5   % Fair or Poor Health                                3194 non-null   float64
 6   Average Number of Physically Unhealthy Days          3194 non-null   float64
 7   Average Number of Mentally Unhealthy Days            3194 non-null   float64
 8   % Low Birthweight                                    3096 non-null   float64
 9   % Adults Reporting Currently Smoking                 3194 non-null   float64
 10  % Adults with Obesity                                3194 non-null   float64
 11  Food Environment Index                               3159 non-null   float64
 12  % Physically Inactive                                3194 non-null   float64
 13  % With Access to Exercise Opportunities              3149 non-null   float64
 14  % Excessive Drinking                                 3194 non-null   float64
 15  % Driving Deaths with Alcohol Involvement            3167 non-null   float64
 16  Chlamydia Rate                                       3048 non-null   float64
 17  Teen Birth Rate                                      2978 non-null   float64
 18  % Uninsured                                          3193 non-null   float64
 19  Primary Care Physicians Rate                         3037 non-null   float64
 20  Dentist Rate                                         3107 non-null   float64
 21  Mental Health Provider Rate                          3009 non-null   float64
 22  Preventable Hospitalization Rate                     3124 non-null   float64
 23  % with Annual Mammogram                              3172 non-null   float64
 24  % Vaccinated                                         3174 non-null   float64
 25  % Completed High School                              3194 non-null   float64
 26  % Some College                                       3194 non-null   float64
 27  % Unemployed                                         3193 non-null   float64
 28  % Children in Poverty                                3193 non-null   float64
 29  Income Ratio                                         3179 non-null   float64
 30  % Children in Single-Parent Households               3193 non-null   float64
 31  Social Association Rate                              3194 non-null   float64
 32  Injury Death Rate                                    3088 non-null   float64
 33  Average Daily PM2.5                                  3166 non-null   float64
 34  Presence of Water Violation                          3091 non-null   object
 35  % Severe Housing Problems                            3194 non-null   float64
 36  % Drive Alone to Work                                3194 non-null   float64
 37  % Long Commute - Drives Alone                        3194 non-null   float64
 38  Life Expectancy                                      3121 non-null   float64
 39  Age-Adjusted Death Rate                              3139 non-null   float64
 40  Child Mortality Rate                                 2089 non-null   float64
 41  Infant Mortality Rate                                1257 non-null   float64
 42  % Frequent Physical Distress                         3194 non-null   float64
 43  % Frequent Mental Distress                           3194 non-null   float64
 44  % Adults with Diabetes                               3194 non-null   float64
 45  HIV Prevalence Rate                                  2739 non-null   float64
 46  % Food Insecure                                      3194 non-null   float64
 47  % Limited Access to Healthy Foods                    3159 non-null   float64
 48  Drug Overdose Mortality Rate                         1950 non-null   float64
 49  % Insufficient Sleep                                 3191 non-null   float64
 50  % Uninsured Adults                                   3193 non-null   float64
 51  % Uninsured Children                                 3193 non-null   float64
 52  Other Primary Care Provider Rate                     3182 non-null   float64
 53  High School Graduation Rate                          2516 non-null   float64
 54  % Disconnected Youth                                 1224 non-null   float64
 55  Average Grade Performance                            2825 non-null   float64
 56  Average Grade Performance.1                          2738 non-null   float64
 57  Segregation Index                                    2973 non-null   float64
 58  School Funding Adequacy                              3108 non-null   float64
 59  Gender Pay Gap                                       3188 non-null   float64
 60  Median Household Income                              3193 non-null   float64
 61  % Enrolled in Free or Reduced Lunch                  2642 non-null   float64
 62  Segregation Index.1                                  2127 non-null   float64
 63  % Household Income Required for Child Care Expenses  3193 non-null   float64
 64  Child Care Centers per 1,000 Children                3042 non-null   float64
 65  Homicide Rate                                        1427 non-null   float64
 66  Suicide Rate (Age-Adjusted)                          2478 non-null   float64
 67  Firearm Fatalities Rate                              2330 non-null   float64
 68  Motor Vehicle Mortality Rate                         2739 non-null   float64
 69  Juvenile Arrest Rate                                 1946 non-null   float64
 70  % Voter Turnout                                      3163 non-null   float64
 71  % Census Participation                               3141 non-null   float64
 72  Traffic Volume                                       3163 non-null   float64
 73  % Homeowners                                         3194 non-null   float64
 74  % Households with Severe Cost Burden                 3189 non-null   float64
 75  % Households with Broadband Access                   3194 non-null   float64
 76  Population                                           3194 non-null   float64
 77  % Less than 18 Years of Age                          3194 non-null   float64
 78  % 65 and Over                                        3194 non-null   float64
 79  % Black                                              3194 non-null   float64
 80  % American Indian or Alaska Native                   3194 non-null   float64
 81  % Asian                                              3194 non-null   float64
 82  % Native Hawaiian or Other Pacific Islander          3194 non-null   float64
 83  % Hispanic                                           3194 non-null   float64
 84  % Non-Hispanic White                                 3194 non-null   float64
 85  % Not Proficient in English                          3194 non-null   float64
 86  % Female                                             3194 non-null   float64
 87  % Rural                                              3194 non-null   float64
dtypes: float64(84), int64(1), object(3)
memory usage: 2.1+ MB

In [4]:
nan_counts = data.isna().sum(axis=1)
data['NaN_Count'] = nan_counts
sorted_data = data.sort_values(by='NaN_Count', ascending=False)
sorted_data.head(35)

,FIPS,State,County,Deaths,Years of Potential Life Lost Rate,% Fair or Poor Health,Average Number of Physically Unhealthy Days,Average Number of Mentally Unhealthy Days,% Low Birthweight,% Adults Reporting Currently Smoking,...,% Black,% American Indian or Alaska Native,% Asian,% Native Hawaiian or Other Pacific Islander,% Hispanic,% Non-Hispanic White,% Not Proficient in English,% Female,% Rural,NaN_Count
2970,51515,Virginia,Bedford City,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,85
99,2270,Alaska,Wade Hampton,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,85
98,2261,Alaska,Valdez-Cordova,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,85
101,2280,Alaska,Wrangell-Petersburg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,85
93,2201,Alaska,Prince of Wales-Outer Ketchikan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,85
96,2232,Alaska,Skagway-Hoonah-Angoon,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,85
2466,46113,South Dakota,Shannon,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,85
566,15005,Hawaii,Kalawao,NaN,NaN,13.7,2.419794,3.217227,NaN,13.6,...,0.000000,0.000000,7.317073,43.902439,2.439024,32.926829,0.000000,43.902439,100.0,45
74,2063,Alaska,Chugach,NaN,NaN,12.8,3.462937,4.433240,NaN,15.4,...,1.207448,12.816410,7.070119,1.061973,6.284550,66.511493,1.745598,46.115799,100.0,35
75,2066,Alaska,Copper River,NaN,NaN,15.8,3.972858,4.807877,NaN,19.4,...,0.811124,18.733102,2.974121,0.386250,6.952491,63.962920,0.000000,45.925068,100.0,34
102,2282,Alaska,Yakutat,NaN,NaN,17.5,4.055072,5.080561,NaN,21.5,...,2.142857,35.285714,9.000000,1.142857,7.000000,32.285714,1.535509,41.714286,100.0,32
2724,48301,Texas,Loving,NaN,NaN,13.7,3.004865,4.332012,NaN,14.7,...,1.960784,0.000000,3.921569,0.000000,21.568627,72.549020,6.849315,21.568627,100.0,32
2704,48261,Texas,Kenedy,NaN,NaN,27.2,4.605199,5.266932,NaN,18.4,...,2.513966,1.955307,1.675978,0.000000,68.156425,24.022346,36.363636,44.972067,100.0,30
69,2013,Alaska,Aleutians East,NaN,NaN,19.1,3.696286,3.992769,10.752688,18.6,...,10.211889,13.919953,46.380224,0.971160,17.363155,8.887581,14.549864,30.164803,100.0,29
86,2164,Alaska,Lake and Peninsula,NaN,NaN,20.9,4.575602,5.625757,5.851064,25.7,...,1.086169,60.680666,2.896452,0.651702,3.113686,21.723389,0.654308,47.356988,100.0,27
2708,48269,Texas,King,NaN,NaN,25.0,4.724044,5.913805,NaN,23.1,...,2.575107,1.287554,0.000000,0.429185,22.317597,71.244635,7.425743,46.781116,100.0,27
100,2275,Alaska,Wrangell,NaN,NaN,17.4,4.039846,5.549188,NaN,21.9,...,0.579710,16.956522,3.526570,0.096618,4.009662,62.850242,0.050075,46.956522,100.0,27
80,2105,Alaska,Hoonah-Angoon,NaN,NaN,17.7,4.178781,5.409236,NaN,21.4,...,2.055094,38.172278,0.612156,0.174902,6.689987,45.736773,0.576752,45.474421,100.0,27
1746,31117,Nebraska,McPherson,NaN,NaN,13.0,3.083519,4.190239,NaN,16.6,...,0.537634,0.000000,0.268817,0.000000,2.956989,95.161290,0.000000,49.731183,100.0,27
95,2230,Alaska,Skagway,NaN,NaN,13.6,3.523140,4.693478,NaN,17.1,...,1.942646,6.197965,2.867715,0.370028,6.845513,77.520814,1.062092,47.456059,100.0,26
1745,31115,Nebraska,Loup,NaN,NaN,12.6,3.026806,4.175547,NaN,16.8,...,1.502504,0.166945,0.333890,0.000000,4.507513,93.489149,0.000000,49.415693,100.0,26
1665,30069,Montana,Petroleum,NaN,NaN,13.3,3.380797,4.817944,NaN,16.8,...,0.190840,1.908397,0.000000,0.000000,2.290076,94.083969,0.000000,46.946565,100.0,26
1690,31005,Nebraska,Arthur,NaN,NaN,13.4,3.115751,4.216214,NaN,16.6,...,0.000000,0.923788,0.230947,0.000000,4.157044,93.764434,0.000000,50.115473,100.0,26
1682,30103,Montana,Treasure,NaN,NaN,14.9,3.647889,4.946617,NaN,17.9,...,0.000000,2.902375,1.055409,0.000000,5.540897,88.654354,0.000000,49.208443,100.0,26
76,2068,Alaska,Denali,NaN,NaN,14.2,3.535991,4.608646,7.299270,16.9,...,3.406940,6.561514,5.552050,0.063091,5.299685,74.195584,0.441826,45.362776,100.0,25
73,2060,Alaska,Bristol Bay,NaN,NaN,14.4,3.656409,4.490508,NaN,18.7,...,0.693642,31.098266,2.196532,0.346821,11.213873,38.728324,0.000000,46.589595,100.0,25
1670,30079,Montana,Prairie,NaN,NaN,18.3,4.126396,5.364700,NaN,21.3,...,0.451671,1.445348,0.813008,0.000000,4.516712,88.437218,0.000000,48.419151,100.0,25
1685,30109,Montana,Wibaux,NaN,NaN,14.1,3.506491,4.940285,NaN,17.5,...,0.435256,1.414581,0.870511,0.108814,3.482046,91.621328,0.681597,48.748640,100.0,25
2074,38087,North Dakota,Slope,NaN,NaN,12.8,2.922223,3.688145,NaN,15.7,...,1.041667,4.910714,0.000000,0.000000,4.464286,90.922619,0.000000,47.321429,100.0,25
1739,31103,Nebraska,Keya Paha,NaN,NaN,15.0,3.370238,4.369009,NaN,18.9,...,0.000000,0.889454,0.381194,0.000000,0.762389,97.585769,0.000000,47.903431,100.0,25
1649,30037,Montana,Golden Valley,NaN,NaN,15.2,3.660228,5.132907,NaN,18.7,...,0.479042,2.275449,0.718563,0.239521,4.550898,90.179641,0.000000,52.814371,100.0,25
1459,28055,Mississippi,Issaquena,NaN,NaN,31.1,4.681484,5.101795,19.178082,27.5,...,64.807541,0.392773,0.785546,0.078555,2.120974,31.657502,0.000000,31.893166,100.0,25
1692,31009,Nebraska,Blaine,NaN,NaN,12.7,3.087289,4.050082,NaN,16.7,...,0.441501,0.441501,0.000000,0.000000,2.869757,93.818985,0.817439,48.785872,100.0,25
91,2195,Alaska,Petersburg,NaN,NaN,14.2,3.544153,4.935143,NaN,17.4,...,1.875000,10.892857,6.547619,0.922619,7.351190,64.970238,6.788593,48.244048,100.0,25
2034,38007,North Dakota,Billings,NaN,NaN,12.1,2.807954,3.653041,NaN,15.1,...,0.589391,1.080550,3.634578,0.098232,2.652259,91.453831,0.000000,46.758350,100.0,25

In [5]:
alaska = data[data['State']=='Alaska']

In [6]:
alaska

,FIPS,State,County,Deaths,Years of Potential Life Lost Rate,% Fair or Poor Health,Average Number of Physically Unhealthy Days,Average Number of Mentally Unhealthy Days,% Low Birthweight,% Adults Reporting Currently Smoking,...,% Black,% American Indian or Alaska Native,% Asian,% Native Hawaiian or Other Pacific Islander,% Hispanic,% Non-Hispanic White,% Not Proficient in English,% Female,% Rural,NaN_Count
68,2000,Alaska,NaN,9838.0,9414.775658,14.3,3.564454,4.588410,6.368605,17.2,...,3.237943,15.702927,6.729300,1.672476,7.701242,58.795256,1.545281,47.388775,35.100513,7
69,2013,Alaska,Aleutians East,NaN,NaN,19.1,3.696286,3.992769,10.752688,18.6,...,10.211889,13.919953,46.380224,0.971160,17.363155,8.887581,14.549864,30.164803,100.000000,29
70,2016,Alaska,Aleutians West,NaN,NaN,15.3,3.145327,3.815269,7.339450,15.5,...,8.141351,9.000390,38.578680,3.787583,15.755564,23.057399,10.022004,29.129246,100.000000,25
71,2020,Alaska,Anchorage,3864.0,9238.415092,13.5,3.420785,4.598679,6.804820,14.9,...,5.129812,9.541521,10.297585,3.317139,9.944801,55.092375,2.062012,48.744363,4.269229,5
72,2050,Alaska,Bethel,291.0,17063.017584,30.0,5.930766,6.485706,7.522429,35.4,...,0.969491,84.800351,1.046174,0.197185,2.240237,8.139344,1.327861,47.433861,72.693668,7
73,2060,Alaska,Bristol Bay,NaN,NaN,14.4,3.656409,4.490508,NaN,18.7,...,0.693642,31.098266,2.196532,0.346821,11.213873,38.728324,0.000000,46.589595,100.000000,25
74,2063,Alaska,Chugach,NaN,NaN,12.8,3.462937,4.433240,NaN,15.4,...,1.207448,12.816410,7.070119,1.061973,6.284550,66.511493,1.745598,46.115799,100.000000,35
75,2066,Alaska,Copper River,NaN,NaN,15.8,3.972858,4.807877,NaN,19.4,...,0.811124,18.733102,2.974121,0.386250,6.952491,63.962920,0.000000,45.925068,100.000000,34
76,2068,Alaska,Denali,NaN,NaN,14.2,3.535991,4.608646,7.299270,16.9,...,3.406940,6.561514,5.552050,0.063091,5.299685,74.195584,0.441826,45.362776,100.000000,25
77,2070,Alaska,Dillingham,105.0,19921.394190,23.8,4.809272,6.063944,6.493506,29.1,...,0.825746,72.559814,1.122168,0.232903,3.557061,13.995342,1.691094,47.723904,100.000000,15
78,2090,Alaska,Fairbanks North Star,1106.0,7962.403001,13.3,3.594067,4.635148,6.092639,16.0,...,4.769495,8.339276,3.399891,0.633416,8.611938,68.318721,0.776078,46.029615,25.360933,5
79,2100,Alaska,Haines,NaN,NaN,15.8,3.872760,5.249572,NaN,19.7,...,0.680934,10.554475,1.264591,0.000000,4.182879,75.778210,0.000000,47.714008,100.000000,21
80,2105,Alaska,Hoonah-Angoon,NaN,NaN,17.7,4.178781,5.409236,NaN,21.4,...,2.055094,38.172278,0.612156,0.174902,6.689987,45.736773,0.576752,45.474421,100.000000,27
81,2110,Alaska,Juneau,356.0,7141.381690,12.2,3.127423,4.670682,5.457026,14.5,...,1.306612,12.504340,7.325233,1.262427,7.460944,62.976172,0.969470,48.770712,23.249109,7
82,2122,Alaska,Kenai Peninsula,858.0,8331.828054,14.7,3.905533,4.819102,5.503212,17.9,...,0.776075,8.362168,1.941012,0.336134,4.639974,78.770802,0.365133,47.574559,77.400976,9
83,2130,Alaska,Ketchikan Gateway,189.0,7817.198071,14.5,3.412273,4.889863,7.660021,17.9,...,0.997016,14.314824,8.616549,0.392984,5.800160,62.091551,0.737362,48.438978,14.145397,12
84,2150,Alaska,Kodiak Island,143.0,7250.495089,13.7,3.215704,4.331548,3.972366,16.3,...,1.194969,12.413522,24.268868,0.825472,8.852201,47.272013,7.219273,46.383648,27.257461,12
85,2158,Alaska,Kusilvak,158.0,24287.304719,37.5,6.836834,7.173925,7.380952,42.8,...,0.398647,92.111621,0.495289,0.036241,1.763711,2.693887,0.288224,46.424257,100.000000,17
86,2164,Alaska,Lake and Peninsula,NaN,NaN,20.9,4.575602,5.625757,5.851064,25.7,...,1.086169,60.680666,2.896452,0.651702,3.113686,21.723389,0.654308,47.356988,100.000000,27
87,2170,Alaska,Matanuska-Susitna,1425.0,8367.692550,15.3,4.140338,5.109140,5.801731,19.3,...,1.174498,7.014339,1.682771,0.491507,5.774542,77.307743,0.710357,47.662916,50.090119,5
88,2180,Alaska,Nome,196.0,18440.616600,24.8,5.099969,5.840205,7.587253,30.9,...,0.843925,76.248094,1.667514,0.193188,2.155567,12.923233,0.285182,47.361464,100.000000,10
89,2185,Alaska,North Slope,111.0,9270.446853,18.1,3.994626,5.043094,6.588004,23.9,...,1.406756,52.262841,5.830634,1.878760,4.109209,31.318834,1.434665,36.390560,100.000000,15
90,2188,Alaska,Northwest Arctic,120.0,15896.170304,25.6,5.145962,5.845836,8.139535,31.3,...,1.118146,80.412232,1.064260,0.242490,2.869460,9.079887,0.290655,46.571467,100.000000,15
91,2195,Alaska,Petersburg,NaN,NaN,14.2,3.544153,4.935143,NaN,17.4,...,1.875000,10.892857,6.547619,0.922619,7.351190,64.970238,6.788593,48.244048,100.000000,25
92,2198,Alaska,Prince of Wales-Hyder,140.0,14941.238730,19.8,4.578748,5.426019,6.131078,25.0,...,0.637168,42.831858,1.433628,0.548673,4.584071,43.415929,0.308362,45.008850,100.000000,19
93,2201,Alaska,Prince of Wales-Outer Ketchikan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,85
94,2220,Alaska,Sitka,98.0,7358.030326,13.4,3.479364,4.919967,4.393673,16.4,...,0.990217,15.473634,8.410880,0.357910,7.754712,60.319733,0.892857,48.425197,9.340270,16
95,2230,Alaska,Skagway,NaN,NaN,13.6,3.523140,4.693478,NaN,17.1,...,1.942646,6.197965,2.867715,0.370028,6.845513,77.520814,1.062092,47.456059,100.000000,26
96,2232,Alaska,Skagway-Hoonah-Angoon,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,85
97,2240,Alaska,Southeast Fairbanks,113.0,9875.756572,15.6,3.644946,4.571265,4.353933,19.4,...,1.823102,11.024071,2.991027,1.239140,7.263923,71.727674,2.201405,43.056545,100.000000,15
98,2261,Alaska,Valdez-Cordova,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,85
99,2270,Alaska,Wade Hampton,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,85
100,2275,Alaska,Wrangell,NaN,NaN,17.4,4.039846,5.549188,NaN,21.9,...,0.579710,16.956522,3.526570,0.096618,4.009662,62.850242,0.050075,46.956522,100.000000,27
101,2280,Alaska,Wrangell-Petersburg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,85
102,2282,Alaska,Yakutat,NaN,NaN,17.5,4.055072,5.080561,NaN,21.5,...,2.142857,35.285714,9.000000,1.142857,7.000000,32.285714,1.535509,41.714286,100.000000,32
103,2290,Alaska,Yukon-Koyukuk,123.0,18062.327190,25.1,5.195215,5.952207,5.154639,29.8,...,0.791659,68.352964,0.656497,0.193087,2.780460,21.992663,0.080564,45.974126,100.000000,14

In [7]:
dropped_rows = data[data['NaN_Count'] <= 35]

In [8]:
dropped_rows = dropped_rows[dropped_rows['County'].notna()]

In [9]:
state_counts = data['State'].value_counts()

print(state_counts)

State
Texas                   255
Georgia                 160
Virginia                135
Kentucky                121
Missouri                116
Kansas                  106
Illinois                103
North Carolina          101
Iowa                    100
Tennessee                96
Nebraska                 94
Indiana                  93
Ohio                     89
Minnesota                88
Michigan                 84
Mississippi              83
Oklahoma                 78
Arkansas                 76
Wisconsin                73
Pennsylvania             68
South Dakota             68
Florida                  68
Alabama                  68
Louisiana                65
Colorado                 65
New York                 63
California               59
Montana                  57
West Virginia            56
North Dakota             54
South Carolina           47
Idaho                    45
Washington               40
Oregon                   37
Alaska                   36
New Mexico               34
Utah                     30
Maryland                 25
Wyoming                  24
New Jersey               22
Nevada                   18
Maine                    17
Arizona                  16
Vermont                  15
Massachusetts            15
New Hampshire            11
Connecticut               9
Hawaii                    6
Rhode Island              6
Delaware                  4
District of Columbia      2
Name: count, dtype: int64

In [10]:
dropped_rows.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3142 entries, 1 to 3200
Data columns (total 89 columns):
 #   Column                                               Non-Null Count  Dtype
---  ------                                               --------------  -----
 0   FIPS                                                 3142 non-null   int64
 1   State                                                3142 non-null   object
 2   County                                               3142 non-null   object
 3   Deaths                                               2886 non-null   float64
 4   Years of Potential Life Lost Rate                    2886 non-null   float64
 5   % Fair or Poor Health                                3142 non-null   float64
 6   Average Number of Physically Unhealthy Days          3142 non-null   float64
 7   Average Number of Mentally Unhealthy Days            3142 non-null   float64
 8   % Low Birthweight                                    3045 non-null   float64
 9   % Adults Reporting Currently Smoking                 3142 non-null   float64
 10  % Adults with Obesity                                3142 non-null   float64
 11  Food Environment Index                               3108 non-null   float64
 12  % Physically Inactive                                3142 non-null   float64
 13  % With Access to Exercise Opportunities              3097 non-null   float64
 14  % Excessive Drinking                                 3142 non-null   float64
 15  % Driving Deaths with Alcohol Involvement            3116 non-null   float64
 16  Chlamydia Rate                                       2998 non-null   float64
 17  Teen Birth Rate                                      2927 non-null   float64
 18  % Uninsured                                          3142 non-null   float64
 19  Primary Care Physicians Rate                         2985 non-null   float64
 20  Dentist Rate                                         3055 non-null   float64
 21  Mental Health Provider Rate                          2957 non-null   float64
 22  Preventable Hospitalization Rate                     3073 non-null   float64
 23  % with Annual Mammogram                              3121 non-null   float64
 24  % Vaccinated                                         3123 non-null   float64
 25  % Completed High School                              3142 non-null   float64
 26  % Some College                                       3142 non-null   float64
 27  % Unemployed                                         3142 non-null   float64
 28  % Children in Poverty                                3142 non-null   float64
 29  Income Ratio                                         3127 non-null   float64
 30  % Children in Single-Parent Households               3142 non-null   float64
 31  Social Association Rate                              3142 non-null   float64
 32  Injury Death Rate                                    3037 non-null   float64
 33  Average Daily PM2.5                                  3115 non-null   float64
 34  Presence of Water Violation                          3091 non-null   object
 35  % Severe Housing Problems                            3142 non-null   float64
 36  % Drive Alone to Work                                3142 non-null   float64
 37  % Long Commute - Drives Alone                        3142 non-null   float64
 38  Life Expectancy                                      3070 non-null   float64
 39  Age-Adjusted Death Rate                              3088 non-null   float64
 40  Child Mortality Rate                                 2038 non-null   float64
 41  Infant Mortality Rate                                1206 non-null   float64
 42  % Frequent Physical Distress                         3142 non-null   float64
 43  % Frequent Mental Distress                           3142 non-null   float64
 44  % Adults with Diabetes                               3142 non-null   float64
 45  HIV Prevalence Rate                                  2688 non-null   float64
 46  % Food Insecure                                      3142 non-null   float64
 47  % Limited Access to Healthy Foods                    3108 non-null   float64
 48  Drug Overdose Mortality Rate                         1899 non-null   float64
 49  % Insufficient Sleep                                 3139 non-null   float64
 50  % Uninsured Adults                                   3142 non-null   float64
 51  % Uninsured Children                                 3142 non-null   float64
 52  Other Primary Care Provider Rate                     3130 non-null   float64
 53  High School Graduation Rate                          2467 non-null   float64
 54  % Disconnected Youth                                 1173 non-null   float64
 55  Average Grade Performance                            2781 non-null   float64
 56  Average Grade Performance.1                          2694 non-null   float64
 57  Segregation Index                                    2922 non-null   float64
 58  School Funding Adequacy                              3059 non-null   float64
 59  Gender Pay Gap                                       3137 non-null   float64
 60  Median Household Income                              3142 non-null   float64
 61  % Enrolled in Free or Reduced Lunch                  2601 non-null   float64
 62  Segregation Index.1                                  2076 non-null   float64
 63  % Household Income Required for Child Care Expenses  3142 non-null   float64
 64  Child Care Centers per 1,000 Children                2991 non-null   float64
 65  Homicide Rate                                        1376 non-null   float64
 66  Suicide Rate (Age-Adjusted)                          2427 non-null   float64
 67  Firearm Fatalities Rate                              2279 non-null   float64
 68  Motor Vehicle Mortality Rate                         2688 non-null   float64
 69  Juvenile Arrest Rate                                 1919 non-null   float64
 70  % Voter Turnout                                      3112 non-null   float64
 71  % Census Participation                               3139 non-null   float64
 72  Traffic Volume                                       3111 non-null   float64
 73  % Homeowners                                         3142 non-null   float64
 74  % Households with Severe Cost Burden                 3138 non-null   float64
 75  % Households with Broadband Access                   3142 non-null   float64
 76  Population                                           3142 non-null   float64
 77  % Less than 18 Years of Age                          3142 non-null   float64
 78  % 65 and Over                                        3142 non-null   float64
 79  % Black                                              3142 non-null   float64
 80  % American Indian or Alaska Native                   3142 non-null   float64
 81  % Asian                                              3142 non-null   float64
 82  % Native Hawaiian or Other Pacific Islander          3142 non-null   float64
 83  % Hispanic                                           3142 non-null   float64
 84  % Non-Hispanic White                                 3142 non-null   float64
 85  % Not Proficient in English                          3142 non-null   float64
 86  % Female                                             3142 non-null   float64
 87  % Rural                                              3142 non-null   float64
 88  NaN_Count                                            3142 non-null   int64
dtypes: float64(84), int64(2), object(3)
memory usage: 2.2+ MB

In [11]:
state_counts = dropped_rows['State'].value_counts()

print(state_counts)

State
Texas                   254
Georgia                 159
Virginia                133
Kentucky                120
Missouri                115
Kansas                  105
Illinois                102
North Carolina          100
Iowa                     99
Tennessee                95
Nebraska                 93
Indiana                  92
Ohio                     88
Minnesota                87
Michigan                 83
Mississippi              82
Oklahoma                 77
Arkansas                 75
Wisconsin                72
Pennsylvania             67
Alabama                  67
Florida                  67
South Dakota             66
Louisiana                64
Colorado                 64
New York                 62
California               58
Montana                  56
West Virginia            55
North Dakota             53
South Carolina           46
Idaho                    44
Washington               39
Oregon                   36
New Mexico               33
Alaska                   30
Utah                     29
Maryland                 24
Wyoming                  23
New Jersey               21
Nevada                   17
Maine                    16
Arizona                  15
Vermont                  14
Massachusetts            14
New Hampshire            10
Connecticut               8
Rhode Island              5
Hawaii                    4
Delaware                  3
District of Columbia      1
Name: count, dtype: int64

In [13]:
missing_values = data.isnull().sum()

# Filter columns with more than 300 missing values and sort them in descending order
missing_values_filtered = missing_values[missing_values > 300].sort_values(ascending=False) #300 is ~10% of the total number of rows

#print("\nMissing Values per Column (More than 300):")
#print(missing_values_filtered)

In [16]:
missing_values_filtered

% Disconnected Youth                   1977
Infant Mortality Rate                  1944
Homicide Rate                          1774
Juvenile Arrest Rate                   1255
Drug Overdose Mortality Rate           1251
Child Mortality Rate                   1112
Segregation Index.1                    1074
Firearm Fatalities Rate                 871
Suicide Rate (Age-Adjusted)             723
High School Graduation Rate             685
% Enrolled in Free or Reduced Lunch     559
Average Grade Performance.1             463
HIV Prevalence Rate                     462
Motor Vehicle Mortality Rate            462
Average Grade Performance               376
dtype: int64

In [17]:
features_to_drop = missing_values_filtered.index.tolist()

In [18]:
features_to_drop

['% Disconnected Youth',
 'Infant Mortality Rate',
 'Homicide Rate',
 'Juvenile Arrest Rate',
 'Drug Overdose Mortality Rate',
 'Child Mortality Rate',
 'Segregation Index.1',
 'Firearm Fatalities Rate',
 'Suicide Rate (Age-Adjusted)',
 'High School Graduation Rate',
 '% Enrolled in Free or Reduced Lunch',
 'Average Grade Performance.1',
 'HIV Prevalence Rate',
 'Motor Vehicle Mortality Rate',
 'Average Grade Performance']

In [19]:
dropped_both = dropped_rows.drop(columns = features_to_drop)

In [20]:
dropped_both

,FIPS,State,County,Deaths,Years of Potential Life Lost Rate,% Fair or Poor Health,Average Number of Physically Unhealthy Days,Average Number of Mentally Unhealthy Days,% Low Birthweight,% Adults Reporting Currently Smoking,...,% Black,% American Indian or Alaska Native,% Asian,% Native Hawaiian or Other Pacific Islander,% Hispanic,% Non-Hispanic White,% Not Proficient in English,% Female,% Rural,NaN_Count
1,1001,Alabama,Autauga,942.0,9407.948438,17.3,3.910265,5.703204,9.871335,16.9,...,21.011061,0.471895,1.178065,0.122157,3.381917,72.051072,0.366486,51.296039,40.676813,0
2,1003,Alabama,Baldwin,3789.0,8981.575353,15.2,3.730943,5.373666,8.124318,15.0,...,8.224887,0.810761,1.156086,0.066549,5.036216,82.978473,0.786658,51.239069,37.586455,0
3,1005,Alabama,Barbour,579.0,13138.848362,27.3,5.023488,6.014294,12.272491,25.0,...,47.195013,0.724520,0.469522,0.279284,5.099976,45.272403,1.980660,47.122157,65.919994,4
4,1007,Alabama,Bibb,501.0,12675.434581,22.0,4.552795,5.824583,9.828571,22.0,...,20.736196,0.572597,0.290843,0.131788,3.176551,73.996819,0.289182,46.489434,100.000000,3
5,1009,Alabama,Blount,1239.0,11541.495069,18.6,4.246335,5.664851,7.604321,19.6,...,1.727383,0.633486,0.435206,0.131066,10.070238,85.992741,2.195196,50.290698,90.489397,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3196,56037,Wyoming,Sweetwater,672.0,9732.214769,14.4,3.637753,5.213634,10.088093,17.8,...,1.064216,1.523763,0.914258,0.162051,16.645302,78.839037,1.015254,48.073528,10.754164,3
3197,56039,Wyoming,Teton,123.0,4267.876402,10.0,2.544521,4.105952,7.751938,11.1,...,0.712844,1.137974,1.880878,0.158887,15.764160,79.855713,2.550929,47.584489,53.881102,6
3198,56041,Wyoming,Uinta,320.0,11027.136279,14.1,3.405617,4.957677,9.660725,16.8,...,0.511781,1.458092,0.593859,0.159328,10.105253,86.597142,0.671630,48.831595,44.176039,5
3199,56043,Wyoming,Washakie,130.0,8065.688093,13.7,3.378598,4.623766,6.445672,16.4,...,0.427517,1.697111,0.867988,0.090685,14.172820,82.134992,0.378890,48.529602,36.382563,10
3200,56045,Wyoming,Weston,88.0,5905.489557,14.8,3.564866,5.179947,8.272506,19.7,...,0.758017,2.113703,1.501458,0.029155,5.495627,88.571429,0.121230,44.606414,100.000000,9

In [21]:
dropped_both.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3142 entries, 1 to 3200
Data columns (total 74 columns):
 #   Column                                               Non-Null Count  Dtype
---  ------                                               --------------  -----
 0   FIPS                                                 3142 non-null   int64
 1   State                                                3142 non-null   object
 2   County                                               3142 non-null   object
 3   Deaths                                               2886 non-null   float64
 4   Years of Potential Life Lost Rate                    2886 non-null   float64
 5   % Fair or Poor Health                                3142 non-null   float64
 6   Average Number of Physically Unhealthy Days          3142 non-null   float64
 7   Average Number of Mentally Unhealthy Days            3142 non-null   float64
 8   % Low Birthweight                                    3045 non-null   float64
 9   % Adults Reporting Currently Smoking                 3142 non-null   float64
 10  % Adults with Obesity                                3142 non-null   float64
 11  Food Environment Index                               3108 non-null   float64
 12  % Physically Inactive                                3142 non-null   float64
 13  % With Access to Exercise Opportunities              3097 non-null   float64
 14  % Excessive Drinking                                 3142 non-null   float64
 15  % Driving Deaths with Alcohol Involvement            3116 non-null   float64
 16  Chlamydia Rate                                       2998 non-null   float64
 17  Teen Birth Rate                                      2927 non-null   float64
 18  % Uninsured                                          3142 non-null   float64
 19  Primary Care Physicians Rate                         2985 non-null   float64
 20  Dentist Rate                                         3055 non-null   float64
 21  Mental Health Provider Rate                          2957 non-null   float64
 22  Preventable Hospitalization Rate                     3073 non-null   float64
 23  % with Annual Mammogram                              3121 non-null   float64
 24  % Vaccinated                                         3123 non-null   float64
 25  % Completed High School                              3142 non-null   float64
 26  % Some College                                       3142 non-null   float64
 27  % Unemployed                                         3142 non-null   float64
 28  % Children in Poverty                                3142 non-null   float64
 29  Income Ratio                                         3127 non-null   float64
 30  % Children in Single-Parent Households               3142 non-null   float64
 31  Social Association Rate                              3142 non-null   float64
 32  Injury Death Rate                                    3037 non-null   float64
 33  Average Daily PM2.5                                  3115 non-null   float64
 34  Presence of Water Violation                          3091 non-null   object
 35  % Severe Housing Problems                            3142 non-null   float64
 36  % Drive Alone to Work                                3142 non-null   float64
 37  % Long Commute - Drives Alone                        3142 non-null   float64
 38  Life Expectancy                                      3070 non-null   float64
 39  Age-Adjusted Death Rate                              3088 non-null   float64
 40  % Frequent Physical Distress                         3142 non-null   float64
 41  % Frequent Mental Distress                           3142 non-null   float64
 42  % Adults with Diabetes                               3142 non-null   float64
 43  % Food Insecure                                      3142 non-null   float64
 44  % Limited Access to Healthy Foods                    3108 non-null   float64
 45  % Insufficient Sleep                                 3139 non-null   float64
 46  % Uninsured Adults                                   3142 non-null   float64
 47  % Uninsured Children                                 3142 non-null   float64
 48  Other Primary Care Provider Rate                     3130 non-null   float64
 49  Segregation Index                                    2922 non-null   float64
 50  School Funding Adequacy                              3059 non-null   float64
 51  Gender Pay Gap                                       3137 non-null   float64
 52  Median Household Income                              3142 non-null   float64
 53  % Household Income Required for Child Care Expenses  3142 non-null   float64
 54  Child Care Centers per 1,000 Children                2991 non-null   float64
 55  % Voter Turnout                                      3112 non-null   float64
 56  % Census Participation                               3139 non-null   float64
 57  Traffic Volume                                       3111 non-null   float64
 58  % Homeowners                                         3142 non-null   float64
 59  % Households with Severe Cost Burden                 3138 non-null   float64
 60  % Households with Broadband Access                   3142 non-null   float64
 61  Population                                           3142 non-null   float64
 62  % Less than 18 Years of Age                          3142 non-null   float64
 63  % 65 and Over                                        3142 non-null   float64
 64  % Black                                              3142 non-null   float64
 65  % American Indian or Alaska Native                   3142 non-null   float64
 66  % Asian                                              3142 non-null   float64
 67  % Native Hawaiian or Other Pacific Islander          3142 non-null   float64
 68  % Hispanic                                           3142 non-null   float64
 69  % Non-Hispanic White                                 3142 non-null   float64
 70  % Not Proficient in English                          3142 non-null   float64
 71  % Female                                             3142 non-null   float64
 72  % Rural                                              3142 non-null   float64
 73  NaN_Count                                            3142 non-null   int64
dtypes: float64(69), int64(2), object(3)
memory usage: 1.8+ MB

In [24]:
def impute_with_mean(df):
    for column in df.columns:
        if column != 'State' and column != 'County' and column != 'Presence of Water Violation':  # Skip the 'state' column
            # Calculate the mean of the column grouped by 'state'
            mean_values = df.groupby('State')[column].transform('mean')
            # Fill NaN values with the calculated means
            df[column] = df[column].fillna(mean_values)
    return df

# Impute missing values
dropped_imputed = impute_with_mean(dropped_both)

In [28]:
dropped_imputed['NaN_Count']

1        0
2        0
3        4
4        3
5        0
        ..
3196     3
3197     6
3198     5
3199    10
3200     9
Name: NaN_Count, Length: 3142, dtype: int64

In [31]:
dropped_imputed.tail(5)

,FIPS,State,County,Deaths,Years of Potential Life Lost Rate,% Fair or Poor Health,Average Number of Physically Unhealthy Days,Average Number of Mentally Unhealthy Days,% Low Birthweight,% Adults Reporting Currently Smoking,...,% Black,% American Indian or Alaska Native,% Asian,% Native Hawaiian or Other Pacific Islander,% Hispanic,% Non-Hispanic White,% Not Proficient in English,% Female,% Rural,NaN_Count
3196,56037,Wyoming,Sweetwater,672.0,9732.214769,14.4,3.637753,5.213634,10.088093,17.8,...,1.064216,1.523763,0.914258,0.162051,16.645302,78.839037,1.015254,48.073528,10.754164,3
3197,56039,Wyoming,Teton,123.0,4267.876402,10.0,2.544521,4.105952,7.751938,11.1,...,0.712844,1.137974,1.880878,0.158887,15.764160,79.855713,2.550929,47.584489,53.881102,6
3198,56041,Wyoming,Uinta,320.0,11027.136279,14.1,3.405617,4.957677,9.660725,16.8,...,0.511781,1.458092,0.593859,0.159328,10.105253,86.597142,0.671630,48.831595,44.176039,5
3199,56043,Wyoming,Washakie,130.0,8065.688093,13.7,3.378598,4.623766,6.445672,16.4,...,0.427517,1.697111,0.867988,0.090685,14.172820,82.134992,0.378890,48.529602,36.382563,10
3200,56045,Wyoming,Weston,88.0,5905.489557,14.8,3.564866,5.179947,8.272506,19.7,...,0.758017,2.113703,1.501458,0.029155,5.495627,88.571429,0.121230,44.606414,100.000000,9

In [37]:
nan_counts = dropped_imputed.isna().sum(axis=1)
dropped_imputed['NaN_Count'] = nan_counts
sorted_data = dropped_imputed.sort_values(by='NaN_Count', ascending=False)

In [42]:
sorted_data.notna().iloc[1]

FIPS                                 True
State                                True
County                               True
Deaths                               True
Years of Potential Life Lost Rate    True
                                     ...
% Non-Hispanic White                 True
% Not Proficient in English          True
% Female                             True
% Rural                              True
NaN_Count                            True
Name: 568, Length: 74, dtype: bool

In [43]:
nan_columns = sorted_data.columns[sorted_data.isna().iloc[1]].tolist()

In [44]:
nan_columns

['Presence of Water Violation', 'School Funding Adequacy']

In [47]:
dropped_imputed.to_csv('dropped_imputed.csv')

In [48]:
dropped_imputed.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3142 entries, 1 to 3200
Data columns (total 74 columns):
 #   Column                                               Non-Null Count  Dtype
---  ------                                               --------------  -----
 0   FIPS                                                 3142 non-null   int64
 1   State                                                3142 non-null   object
 2   County                                               3142 non-null   object
 3   Deaths                                               3142 non-null   float64
 4   Years of Potential Life Lost Rate                    3142 non-null   float64
 5   % Fair or Poor Health                                3142 non-null   float64
 6   Average Number of Physically Unhealthy Days          3142 non-null   float64
 7   Average Number of Mentally Unhealthy Days            3142 non-null   float64
 8   % Low Birthweight                                    3142 non-null   float64
 9   % Adults Reporting Currently Smoking                 3142 non-null   float64
 10  % Adults with Obesity                                3142 non-null   float64
 11  Food Environment Index                               3142 non-null   float64
 12  % Physically Inactive                                3142 non-null   float64
 13  % With Access to Exercise Opportunities              3142 non-null   float64
 14  % Excessive Drinking                                 3142 non-null   float64
 15  % Driving Deaths with Alcohol Involvement            3142 non-null   float64
 16  Chlamydia Rate                                       3118 non-null   float64
 17  Teen Birth Rate                                      3142 non-null   float64
 18  % Uninsured                                          3142 non-null   float64
 19  Primary Care Physicians Rate                         3142 non-null   float64
 20  Dentist Rate                                         3142 non-null   float64
 21  Mental Health Provider Rate                          3142 non-null   float64
 22  Preventable Hospitalization Rate                     3142 non-null   float64
 23  % with Annual Mammogram                              3142 non-null   float64
 24  % Vaccinated                                         3142 non-null   float64
 25  % Completed High School                              3142 non-null   float64
 26  % Some College                                       3142 non-null   float64
 27  % Unemployed                                         3142 non-null   float64
 28  % Children in Poverty                                3142 non-null   float64
 29  Income Ratio                                         3142 non-null   float64
 30  % Children in Single-Parent Households               3142 non-null   float64
 31  Social Association Rate                              3142 non-null   float64
 32  Injury Death Rate                                    3142 non-null   float64
 33  Average Daily PM2.5                                  3142 non-null   float64
 34  Presence of Water Violation                          3091 non-null   object
 35  % Severe Housing Problems                            3142 non-null   float64
 36  % Drive Alone to Work                                3142 non-null   float64
 37  % Long Commute - Drives Alone                        3142 non-null   float64
 38  Life Expectancy                                      3142 non-null   float64
 39  Age-Adjusted Death Rate                              3142 non-null   float64
 40  % Frequent Physical Distress                         3142 non-null   float64
 41  % Frequent Mental Distress                           3142 non-null   float64
 42  % Adults with Diabetes                               3142 non-null   float64
 43  % Food Insecure                                      3142 non-null   float64
 44  % Limited Access to Healthy Foods                    3142 non-null   float64
 45  % Insufficient Sleep                                 3142 non-null   float64
 46  % Uninsured Adults                                   3142 non-null   float64
 47  % Uninsured Children                                 3142 non-null   float64
 48  Other Primary Care Provider Rate                     3142 non-null   float64
 49  Segregation Index                                    3142 non-null   float64
 50  School Funding Adequacy                              3124 non-null   float64
 51  Gender Pay Gap                                       3142 non-null   float64
 52  Median Household Income                              3142 non-null   float64
 53  % Household Income Required for Child Care Expenses  3142 non-null   float64
 54  Child Care Centers per 1,000 Children                3142 non-null   float64
 55  % Voter Turnout                                      3112 non-null   float64
 56  % Census Participation                               3142 non-null   float64
 57  Traffic Volume                                       3142 non-null   float64
 58  % Homeowners                                         3142 non-null   float64
 59  % Households with Severe Cost Burden                 3142 non-null   float64
 60  % Households with Broadband Access                   3142 non-null   float64
 61  Population                                           3142 non-null   float64
 62  % Less than 18 Years of Age                          3142 non-null   float64
 63  % 65 and Over                                        3142 non-null   float64
 64  % Black                                              3142 non-null   float64
 65  % American Indian or Alaska Native                   3142 non-null   float64
 66  % Asian                                              3142 non-null   float64
 67  % Native Hawaiian or Other Pacific Islander          3142 non-null   float64
 68  % Hispanic                                           3142 non-null   float64
 69  % Non-Hispanic White                                 3142 non-null   float64
 70  % Not Proficient in English                          3142 non-null   float64
 71  % Female                                             3142 non-null   float64
 72  % Rural                                              3142 non-null   float64
 73  NaN_Count                                            3142 non-null   int64
dtypes: float64(69), int64(2), object(3)
memory usage: 1.8+ MB